### ISSUE TITLE
Max Submission Size

### ISSUE THREAD

**Issue by NoelShin** [LUSSeg/ImageNet-S#4]
Dear the authors,

Thanks a lot for the great efforts for LUSS!

While I was hoping to submit a result file in a zip format as in the provided example submission file, I noticed that submitting for the ImageNet-S300 and ImageNet-S919 test splits requires 30MB max submission size. When I tried a maximum compression using zip command to make the resulting zip file small, it is still over 30MB (~35MB) for ImageNet-S300, thus couldn't successfully submit.

Is there any way that the authors used to compress the results to meet the required max submission size of 30MB for ImageNet-S300 and ImageNet-S919?

Kind regards,
noel

**Comment by gasvn** [comment]
Hi noel,
   Thanks for the feedback. We have changed the max submission size to 300MB. You can try it again now.  We notice that different results have different zipped sizes. We didn't use any special zip method.
Please let us know if you still cannot submit your results. Also, any other questions are welcomed. Just reach us if you have any other questions or suggestions about our benchmark.

With regard,
Shanghua Gao


________________________________
发件人: Gyungin Shin ***@***.***>
发送时间: 2022年8月12日 3:16
收件人: LUSSeg/ImageNet-S ***@***.***>
抄送: Subscribed ***@***.***>
主题: [LUSSeg/ImageNet-S] Max Submission Size (Issue #4)


Dear the authors,

Thanks a lot for the great efforts for LUSS!

While I was hoping to submit a result file in a zip format as in the provided example submission file, I noticed that submitting for the ImageNet-S300 and ImageNet-S919 test splits requires 30MB max submission size. When I tried a maximum compression using zip command to make the resulting zip file small, it is still over 30MB (~35MB) for ImageNet-S300, thus couldn't successfully submit.

Is there any way that the authors used to compress the results to meet the required max submission size of 30MB for ImageNet-S300 and ImageNet-S919?

Kind regards,
noel

―

**Comment by NoelShin** [comment]
Thank you very much for prompt reply!
I could confirm that the submissions for all ImageNet-S variants are successful after raising the maximum size. :)
