### ISSUE TITLE
Download benchmarking segmentation results

### ISSUE THREAD

**Issue by Michaelsqj** [LUSSeg/ImageNet-S#5]
Hi there,

Thank you for sharing the amazing work. I'm interested in extracting out the objects in imagenet for our own project. May I ask is there any way to download the best segmentation results using the method mentioned in your paper? Or do you suggest any other  methods that has done the segmentation on imagenet, either supervised or unsupervised.

**Comment by gasvn** [comment]
Thanks for your interest in our work. We will open source a semi-supervised codebase and pretrained model in one or two weeks. It can achieve the best performance so far. You can infer the segmentation mask by then. Please let me know if you have any other questions.

**Comment by gasvn** [comment]
The code is now released on https://github.com/LUSSeg/ImageNetSegModel

**Comment by Michaelsqj** [comment]
Thank you very much! It's very helpful!
